"""third migration

Revision ID: 5397e3af89e6
Revises: 063d8adc3719
Create Date: 2020-09-22 16:12:51.082816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5397e3af89e6'
down_revision = '063d8adc3719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=225), nullable=True))
    op.drop_column('users', 'aboutme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aboutme', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
